In [1]:
import torch
import torchvision
import numpy as np

In [54]:
from torchvision import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split

In [73]:
blobs=make_blobs(n_samples=100,n_features=10,centers=4)

In [74]:
blobs[1] 

array([2, 2, 2, 3, 0, 3, 2, 2, 2, 1, 3, 0, 3, 1, 1, 2, 1, 0, 1, 1, 1, 3,
       0, 3, 3, 0, 0, 1, 2, 1, 2, 0, 2, 0, 2, 2, 1, 1, 0, 3, 3, 2, 3, 2,
       3, 2, 3, 0, 2, 1, 3, 0, 3, 0, 2, 3, 3, 0, 2, 0, 3, 3, 2, 1, 2, 1,
       3, 1, 3, 0, 1, 0, 0, 1, 1, 0, 2, 0, 1, 1, 3, 3, 3, 0, 0, 0, 1, 0,
       0, 3, 1, 0, 2, 1, 3, 2, 1, 2, 1, 2])

In [75]:
X_train,X_test,Y_train,Y_test=train_test_split(blobs[0],blobs[1])


In [76]:
# # CIFAR 10 Dataset
# Cifar_train= datasets.CIFAR10('/Users/macbook07/Documents/Piyush/data',train=True,download=True)
# Cifar_test= datasets.CIFAR10('/Users/macbook07/Documents/Piyush/data',train=False,download=True)
# X_train=Cifar_train.data
# X_train=np.reshape(X_train,(50000,-1))
# Y_train=Cifar_train.targets
# X_test=Cifar_test.data
# X_test=np.reshape(X_test,(10000,-1))
# Y_test=Cifar_test.targets

In [92]:
model1=KNeighborsClassifier(n_neighbors=50)
model1.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=50)

In [93]:
model1.score(X_test,Y_test)

0.08

In [94]:
class KNN:
    def __init__(self,k) -> None:
        self.K=k

    def fit(self,X,Y):
        self.X_train=X
        self.Y_train=Y

    def predict(self,X):
        self.distance=[]
        for i in self.X_train:
            self.distance.append(np.sqrt(np.sum(np.square(i-X))))
        
        self.Nearest_neigh=np.argsort(self.distance)[:self.K]
        # print(type(Nearest_neigh))
        # print(len(Nearest_neigh))
        # print(self.Y_train)
        pred=[]
        for j in self.Nearest_neigh:
            pred.append(self.Y_train[j])
        return pred

    
    def score(self,X,Y):
        row=X.shape[0]
        count=0
        for i in range(row):
           nearest_neigh=self.predict(X[i])
           Y_pred=np.bincount(nearest_neigh).argmax()
           if Y_pred==Y[i]:
               count=count+1
        return count/row



In [33]:
X=np.array([[-1,2],[1,2],[1,1],[1,3],[4,2],[4,5],[4,6],[5,6]])
Y=np.array([0,0,0,0,1,1,1,1])

In [95]:
model2=KNN(50)
model2.fit(X_train,Y_train)


In [97]:
model2.score(X_test,Y_test)

0.08

In [73]:
output=np.array([1,1,0,0,2,2,3,3])
distance=np.array([4,2,5,1,6,4,2,4])
index=np.argsort(distance)[:3]

In [74]:
output[index]

array([0, 1, 3])

In [40]:
index

array([3, 1, 6, 0, 5, 7, 2, 4])

In [34]:
type(index[0])

numpy.int64

In [35]:
output[index]

array([0, 1, 3, 1, 2, 3, 0, 2])

In [76]:
distance

array([4, 2, 5, 1, 6, 4, 2, 4])

In [74]:
from collections import Counter
occ=Counter(distance)
occ.most_common

<bound method Counter.most_common of Counter({4: 3, 2: 2, 5: 1, 1: 1, 6: 1})>

In [99]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [100]:
np.sum(a,axis=1)

array([10, 26])

In [53]:
distance[:1]

[2]

In [88]:
a.shape

(2, 2)

In [47]:
for i in a:
    print(i)
    print("cisn")

[1 2 3]
cisn
[2 4 5]
cisn


In [42]:
np.sqrt(np.sum(np.square(a-b)))

3.0